### ISSUE TITLE
NETWORKING add meteor.js for front end framework.

### ISSUE THREAD

**Issue by roo2** [aletheia-foundation/aletheia-app#44]
- [ ] Add meteor
- [ ] Scss 
- [ ] Integrate with Electron
- [ ] Unit test
- [ ] Slides for Ethereum meetup

**Comment by KadeMorton** [comment]
Is this going ahead? I vaguely remember a conversation around meteor being not the way we wanted to go.

**Comment by roo2** [comment]
yea it's not going ahead, I might make something else if we need to add another framework but nothing for now
