### ISSUE TITLE
Add Angular to app

### ISSUE THREAD

**Issue by KadeMorton** [aletheia-foundation/aletheia-app#61]
## I confirm:

- [x] I've read the [contributing guidelines](https://github.com/aletheia-foundation/aletheia-admin/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/aletheia-foundation/aletheia-admin/blob/master/CODE-OF-CONDUCT.md)
- [x] I've checked that this issue applies to this repo
- [x] I've checked the existing issues, no one else has reported this
- [x] I've got a clear and descriptive title for the issue

**Comment by roo2** [comment]
- [ Display Balance and Network Status ] 
- [ Migrate credit account screen ]
- [ Migrate list articles screen ]

**Comment by roo2** [comment]
merged!
